# Generated by Django 3.1.14 on 2022-12-13 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_assignedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
