# Generated by Django 3.1.14 on 2022-12-14 12:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0010_auto_20221214_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('operating_system', models.CharField(choices=[(1, 'Windows'), (2, 'Linux'), (3, 'Kali Linux'), (4, 'BackBox'), (5, 'Parrot Security Operating System'), (6, 'DEFT Linux'), (7, 'Samurai Web Testing Framework'), (8, 'Network Security Toolkit'), (9, 'BlackArch Linux'), (10, 'Cyborg Hawk Linux'), (11, 'GnackTrack'), (12, 'CNodeZero')], default=1, max_length=3)),
                ('scenarios', models.CharField(choices=[(1, 'Active Directory Attack'), (2, 'OS Exploitation')], default=1, max_length=50)),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.course')),
            ],
        ),
    ]
