# Generated by Django 3.1.14 on 2022-12-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0011_virtualnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnetwork',
            name='operating_system',
            field=models.CharField(choices=[('1', 'Windows'), ('2', 'Linux'), ('3', 'Kali Linux'), ('4', 'BackBox'), ('5', 'Parrot Security Operating System'), ('6', 'DEFT Linux'), ('7', 'Samurai Web Testing Framework'), ('8', 'Network Security Toolkit'), ('9', 'BlackArch Linux'), ('10', 'Cyborg Hawk Linux'), ('11', 'GnackTrack'), ('12', 'CNodeZero')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='virtualnetwork',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='virtualnetwork',
            name='scenarios',
            field=models.CharField(choices=[('1', 'Active Directory Attack'), ('2', 'OS Exploitation')], default=1, max_length=50),
        ),
    ]
