# Generated by Django 3.1.14 on 2022-12-15 00:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0012_auto_20221215_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnetwork',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='virtualnetwork',
            name='scenarios',
            field=models.CharField(choices=[('1', 'Active Directory Attack'), ('2', 'OS Exploitation')], default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='CourseChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('levels', models.CharField(choices=[('1', 'EASY'), ('2', 'MEDIUM'), ('3', 'HARD')], default='1', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.course')),
            ],
        ),
    ]
