# Generated by Django 3.1.14 on 2022-12-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0013_auto_20221215_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnetwork',
            name='scenarios',
            field=models.CharField(choices=[('1', 'Active Directory Attack'), ('2', 'OS Exploitation'), ('3', 'Privilege Escalation on Linux OS'), ('4', 'Privilege Escalation / RCE-Command Injection / Brute Force')], default='1', max_length=50),
        ),
    ]
