# Generated by Django 3.1.14 on 2022-12-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0014_auto_20221215_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_approved',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Sent Admin for Approval'), ('3', 'Approved'), ('4', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
