# Generated by Django 3.1.14 on 2022-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0015_auto_20221215_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_approved',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Sent Admin for Approval'), ('3', 'Approved'), ('4', 'Rejected')], default='1', max_length=2),
        ),
    ]
