# Generated by Django 3.1.14 on 2022-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0016_auto_20221215_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnetwork',
            name='config_file_url',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
