# Generated by Django 3.1.14 on 2022-12-15 19:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0017_virtualnetwork_config_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnetwork',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='virtualnetwork',
            name='ssh_file',
            field=models.FileField(blank=True, null=True, upload_to='sshFiles/'),
        ),
        migrations.AddField(
            model_name='virtualnetwork',
            name='topology_image',
            field=models.ImageField(blank=True, null=True, upload_to='topologies/'),
        ),
    ]
