# Generated by Django 3.1.14 on 2022-12-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0019_coursechallenge_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUBMITTED', 'SUBMITTED')], default='PENDING', max_length=100, null=True)),
                ('submitted_answer', models.TextField(blank=True, max_length=200, null=True)),
                ('obtained_points', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assinged_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.assignedstudents')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.coursechallenge')),
            ],
        ),
    ]
