# Generated by Django 3.1.14 on 2022-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0020_challengesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
