# Generated by Django 3.1.14 on 2022-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0021_course_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='attempts',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
