# Generated by Django 3.1.14 on 2022-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0022_challengesubmission_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechallenge',
            name='original_flag',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
