# Generated by Django 3.1.14 on 2022-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0023_coursechallenge_original_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
