# Generated by Django 3.1.14 on 2022-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0024_auto_20221219_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnetwork',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1', max_length=1, null=True),
        ),
    ]
