# Generated by Django 3.1.14 on 2022-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0025_auto_20221221_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnetwork',
            name='is_instance_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
