# Generated by Django 3.1.14 on 2022-12-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0026_virtualnetwork_is_instance_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnetwork',
            name='imageRef',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
