# Generated by Django 3.1.14 on 2022-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0030_auto_20221222_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualnetwork',
            name='server_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
