# Generated by Django 3.1.14 on 2022-12-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0031_virtualnetwork_server_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('points', models.IntegerField(blank=True, default=50, null=True)),
                ('original_answer', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('imageRef', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.course')),
            ],
        ),
    ]
