# Generated by Django 3.1.14 on 2023-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0034_networkflagsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to='courses/'),
        ),
    ]
