# Generated by Django 3.1.14 on 2023-01-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0035_course_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedstudents',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'ATTACKER'), ('2', 'DEFENSER')], default='1', max_length=2),
        ),
    ]
