# Generated by Django 3.1.14 on 2023-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0036_assignedstudents_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('1', 'ATTACK'), ('2', 'ATTACH-DEEFENSE')], default='1', max_length=1, null=True),
        ),
    ]
