# Generated by Django 3.1.14 on 2023-02-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0037_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkflagsubmission',
            name='original_answer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
