# Generated by Django 3.1.14 on 2023-02-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0038_networkflagsubmission_original_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_flags',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
