# Generated by Django 3.1.14 on 2023-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0039_course_number_of_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug_name',
            field=models.SlugField(blank=True, default='', help_text='Slugify title of event', max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
