# Generated by Django 3.1.14 on 2023-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0040_course_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug_name',
            field=models.SlugField(blank=True, default='', help_text='Slugify title of event', max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
