"""
Django settings for cys_games project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SITE_ID = config('SITE_ID', cast=int)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

OPENSTACK=config('OPENSTACK')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
# ALLOWED_HOSTS = ['2351-2400-adca-102-9900-443b-2c87-3490-1a68.in.ngrok.io']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',          
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    # 'django.contrib.flatpages',

    'rest_framework',

    # Custom Django User Model
    'accounts',

    # local apps
    'master_app',

    "ckeditor",

    'api',

    'sorl.thumbnail',

    'django.contrib.humanize',

    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cys_games.urls'
AUTH_USER_MODEL = 'accounts.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'master_app/templates/master_app',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cys_games.wsgi.application'


# Set Default User Model
# AUTH_USER_MODEL = 'master_app.User'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / config('DB_NAME'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= BASE_DIR / 'static'
STATICFILES_DIRS=[
]

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT= BASE_DIR.parent / 'media'


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

CKEDITOR_UPLOAD_PATH = "uploads/"


# ? Login Redirect

from django.urls import reverse_lazy

LOGIN_REDIRECT_URL = reverse_lazy('master_index')
LOGIN_URL = reverse_lazy('user-login')
LOGOUT_URL = reverse_lazy('user-logout')

# OpenStack configurtaions
OPENSTACK_USER=config('OPENSTACK_USER')
OPENSTACK_PASSWORD=config('OPENSTACK_PASSWORD')
OPENSTACK_AUTHORIZED_URL=config('OPENSTACK_AUTHORIZED_URL')
OPENSTACK_IMAGE_URL=config('OPENSTACK_IMAGE_URL')
OPENSTACK_SERVER_URL=config('OPENSTACK_SERVER_URL')
OPENSTACK_FLOATING_IP_URL=config('OPENSTACK_FLOATING_IP_URL')
OPENSTACK_FLAVOR_URL=config('OPENSTACK_FLAVOR_URL')
OPENSTACK_NETWORK_UUID=config('OPENSTACK_NETWORK_UUID')
OPENSTACK_DC_UUID=config('OPENSTACK_DC_UUID')
OPENSTACK_NETWORK_POOL=config('OPENSTACK_NETWORK_POOL')
IS_SPAWN_DC=config('IS_SPAWN_DC', cast=bool)
DC_CLIENT_SERVER=config("DC_CLIENT_SERVER")
OPENSTACK_NETWORK_LABEL=config('OPENSTACK_NETWORK_LABEL')
OPENSTACK_OS_TYPE=config('OPENSTACK_OS_TYPE')
WAZUH_SERVER_PUBLIC_IP=config('WAZUH_SERVER_PUBLIC_IP')
DC_IP_ADDRESS=config('DC_IP_ADDRESS')
WAZUH_SERVER_PASSWORD=config('WAZUH_SERVER_PASSWORD')