# Generated by Django 3.1.14 on 2022-12-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221211_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_instructor',
        ),
    ]
