# Generated by Django 3.1.14 on 2022-12-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221211_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
        ),
    ]
