# Generated by Django 3.1.14 on 2023-01-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221213_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vpn_file',
            field=models.FileField(blank=True, upload_to='vpn/'),
        ),
    ]
